# Generated by Django 4.0.3 on 2022-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('user_hand', models.CharField(max_length=200)),
                ('user_stack', models.CharField(max_length=200)),
                ('player_names', models.CharField(max_length=200)),
                ('player_hands', models.CharField(max_length=200)),
                ('player_stacks', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=200)),
                ('user_stack_length', models.IntegerField()),
                ('table_log', models.CharField(max_length=400)),
                ('hand_name', models.CharField(max_length=200)),
            ],
        ),
    ]
